### ISSUE TITLE
adding creational design pattern and structural design pattern code examples 

### ISSUE THREAD

**Issue by Mariihmp** [3lf/design-patterns-for-humans#40]
I found your project very intuitive, I wanted to ask if is it possible to add code bases for the two design patterns that i mentioned above or it was intentionally left blank in the first place

**Comment by 3lf** [comment]
Thank you for bringing this up, and I’m sorry for any confusion caused by the structure of the repository.

To clarify, we have three main categories of design patterns:
	•	Creational Design Patterns
	•	Structural Design Patterns
	•	Behavioral Design Patterns

Each of these titles represents a category that includes several specific design patterns. They are not individual design patterns themselves, which is why there are no examples provided for them specifically.

I really appreciate your feedback and will consider adjusting the repository structure to prevent such misunderstandings in the future.

Thanks again for your input! 😊
